AWS_CRED_DEF = $(HOME)/.aws/credentials 
.PHONY: build

build: passwd-s3fs

passwd-s3fs:
	@if [ -f $(AWS_CRED_DEF) ]; then \
        echo Found $(AWS_CRED_DEF). Do you want use it for ...... TODO ; \
    fi

